eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 120
    lease-renewal-interval-in-seconds: 60
    healthcheck:
    enabled: true
server:
  port: 8762
spring:
  application:
    name: service-hi